name: Build Project

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:   # 👈 thêm dòng này để có nút bấm

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3

      - name: Build solution
        run: msbuild sampvoice.sln /p:Configuration=Release
