name: Build Project

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install DirectX 9 SDK
        run: choco install directx-sdk -y

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet
        run: nuget restore sampvoice.sln

      - name: Build
        run: msbuild sampvoice.sln /p:Configuration=Release /p:Platform=x86 /p:WindowsTargetPlatformVersion=10.0
